name: annotate_frequency-env
dependencies:
  - zlib
  - bzip2
  - git
  - boost
  - finter
# required for commitizen
  - nodejs
  - pre-commit
  - cppcheck
  - sarcasm::clang-format
  - automake
  - autoconf
  - make>=4.2
  - gxx_linux-64>=8.2.0
  - libtool
  
